apiVersion: apps/v1
kind: Deployment
metadata:
  name: ub-deployment
spec:
  selector:
    matchLabels:
      app: ub-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ub-app
    spec:
      containers:
      - name: ub-webssh
        image: zhujq/ub-webssh
        ports:
            - containerPort: 8888
              protocol: TCP
        resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
