apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: zhujq/ub-webssh # the same image name that is used in Deployment manifest
#  - image: flask-hello-world-img # the same image name that is used in Deployment manifest
deploy:
  kubectl:
    manifests:
      - k8s-*
